//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// v_opt.cpp
//
// Code generation for function 'v_opt'
//

// Include files
#include "v_opt.h"
#include "a_opt_mex_data.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

// Function Definitions
real_T v_opt(const emlrtStack *, real_T t, real_T v0, real_T a0, real_T sf,
             real_T vf, real_T af, real_T T)
{
  real_T b_out1_tmp;
  real_T out1_tmp;
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t4_tmp;
  covrtLogFcn(&emlrtCoverageInstance, 14, 0);
  covrtLogBasicBlock(&emlrtCoverageInstance, 14, 0);
  // V_OPT
  //     OUT1 = V_OPT(t,V0,A0,SF,VF,AF,T)
  //     This function was generated by the Symbolic Math Toolbox version 9.2.
  //     12-Dec-2022 17:49:18
  t2 = T * T;
  t3 = af * t2;
  t4_tmp = a0 * t2;
  t4 = t4_tmp * 3.0;
  out1_tmp = T * v0;
  b_out1_tmp = T * vf;
  return (((v0 + a0 * t) -
           1.0 / muDoubleScalarPower(T, 5.0) * muDoubleScalarPower(t, 4.0) *
               ((((sf * -12.0 - t3) + out1_tmp * 6.0) + b_out1_tmp * 6.0) +
                t4_tmp) *
               2.5) -
          1.0 / muDoubleScalarPower(T, 3.0) * (t * t) *
              ((((sf * -20.0 + t4) - t3) + out1_tmp * 12.0) +
               b_out1_tmp * 8.0) *
              1.5) +
         muDoubleScalarPower(t, 3.0) / (t2 * t2) *
             ((((sf * -30.0 - t3 * 2.0) + t4) + out1_tmp * 16.0) +
              b_out1_tmp * 14.0) *
             2.0;
}

// End of code generation (v_opt.cpp)
